services:
  processing-service:
    container_name: processing-service
    build:
      context: ./processing-service
      dockerfile: Dockerfile
    image: localhost/processing-service:latest
    ports:
      - 8090:8090  
    networks:
      - myservice-net

  api-gateway:
    container_name: api-gateway
    build:
      context: ./api-gateway
      dockerfile: Dockerfile
    image: localhost/api-gateway:latest
    environment:
      SECRET: fantasticjwt
    volumes:
      - type: bind
        source: ./api-gateway/configs/nginx.conf
        target: /usr/local/openresty/nginx/conf/nginx.conf
      - type: bind
        source: ./api-gateway/configs/conf.d
        target: /etc/nginx/conf.d
      - type: bind
        source: ./api-gateway/lua
        target: /usr/local/openresty/nginx/lua
    ports:
      - 8080:8080
    networks:
      - myservice-net

networks:
  myservice-net:
    driver: bridge
